name: Node

on: [pull_request]

jobs:
  build:

    runs-on: windows-2019

    strategy:
      matrix:
        node: [ '14', '12' ]

    name: ${{ matrix.node }} (Windows)
    steps:
    - name: Checkout Commit
      uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: npm install
      run: npm install
    - name: run tests
      run: npm run test

